### ISSUE TITLE
Problem with selects in modal

### ISSUE THREAD

**Issue by cicely-f** [djhi/meteor-autoform-modals-materialize#1]
Hi - I _love_ this package!

I noticed a small issue with fields that use a drop-down: the dropdown renders over the top of most of the form, and if you scroll, then the buttons of the form scroll along with it.

I'd propose adding the `modal-fixed-footer` class to your `<div class="modal">` code that opens the dialog, that fixes it.

**Comment by djhi** [comment]
Thx for reporting the issue. Can you submit a pull request with the
proposed fix ?

**Comment by cicely-f** [comment]
Bien sûr! I'll do that as soon as I've cloned it. :)

**Comment by cicely-f** [comment]
There we go. Pull request sent.
