### ISSUE TITLE
Error concerning the opening of Modal

### ISSUE THREAD

**Issue by ChuaMichelle** [djhi/meteor-autoform-modals-materialize#4]
Hello, 

Running on meteor v 1.1.0.2, I added this package (v0.0.6). 

I just copied the given example here, changed the collection name for the insert method : 

{{#afModal classes="btn" collection="Clients" operation="insert"}}
       Add a new post
{{/afModal}}

And it gives me and error: 

Uncaught TypeError: $(...).openModal is not a function
Template.afModal.events.click \* @ modals.coffee:161
(anonymous function) @ template.js:463
Template._withTemplateInstanceFunc @ template.js:437
(anonymous function) @ template.js:462
(anonymous function) @ view.js:869
Blaze._withCurrentView @ view.js:523
(anonymous function) @ view.js:868
(anonymous function) @ events.js:47
jQuery.event.dispatch @ jquery.js:4665
jQuery.event.add.elemData.handle @ jquery.js:4333

I already have aldeed:autoform package added, is it not compatible with that ? Should I add  gildaspk:autoform-materialize too ? 

Thank you in advance for any advices.
Cheers

**Comment by vladholubiev** [comment]
+1

**Comment by djhi** [comment]
Yes, I did not include `gildaspk:autoform-materialize` nor `materialize:materialize`. You must add them by yourself. Actually, I might add `gildaspk:autoform-materialize` in the next version, but you should be free to include materialize any way you want

**Comment by djhi** [comment]
version `0.0.7` now implies `gildaspk:autoform-materialize` and `aldeed:autoform`
