### ISSUE TITLE
conflict constraint less

### ISSUE THREAD

**Issue by frankcheong** [djhi/meteor-autoform-modals-materialize#6]
while installing gildaspk:autoform-modals-materialize I found that there are conflict with less below:-

While selecting package versions:
error: Conflict: Constraint less@1.0.11 is not satisfied by less 2.5.0_3.
Constraints on package "less":
- less@=2.5.0_3 <- top level
- less@1.0.11 <- gildaspk:autoform-modals-materialize 0.0.7
- less@2.5.0_1 <- multiply:iron-router-progress 1.0.2

anyway I can work around with this?

**Comment by ghost** [comment]
+1

**Comment by mkarliner** [comment]
+1
Workaround is to use a local version of this package with an updated version of less.

**Comment by ALE1VER** [comment]
+1

**Comment by Xsandor** [comment]
+1

**Comment by paulgrieselhuber** [comment]
+1

**Comment by djhi** [comment]
Version `0.0.8` has been published. I'm not using any materialize packages anymore as I use React for all my new projects. If anyone want to keep this project updated, I'll give them rights access here and on atmosphere
